# Generated by Django 5.1 on 2024-08-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fotografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('legenda', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('imagem', models.CharField(max_length=100)),
            ],
        ),
    ]
